name: Deploy to SmarterASP.NET

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        local-dir: ./
        server-dir: ${{ secrets.FTP_REMOTE_PATH }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/
          README.md
